version: "3.4"

services:
  livrariaapi:
    image: ${DOCKER_REGISTRY-}livraria
    build:
      context: .
      dockerfile: .
    ports:
      - "8080:80"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Numsey#2022
      - ACCEPT_EULA=Y
    volumes:
      - G:\volumes\mssql:/var/opt/mssql/data
    ports:
      - "1450:1433"
